data:
  ENV_MODE: release #debug, release, test
  SERVER_PORT: "8080"
  TOKEN_EXPIRE: 8
  SECRET_KEY: "12345678900987654321"
  DATABASE_HOST: 10.247.43.11
  DATABASE_PORT: 11433
  DATABASE_USER: conrms
  DATABASE_PASSWORD: c@nrm$
  DATABASE_NAME: KTBCONRMS_DEV
